version: '2'

services:

  netbox:
    image: ninech/netbox:v2.5.2
    volumes:
      - netbox-nginx-config:/etc/netbox-nginx/
      - netbox-static-files:/opt/netbox/netbox/static
      - netbox-media-files:/opt/netbox/netbox/media
      - netbox-report-files:/etc/netbox/reports:ro
    depends_on:
      - db
    environment:
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: db
      EMAIL_SERVER: localhost
      EMAIL_PORT: 25
      EMAIL_USERNAME: netbox
      EMAIL_PASSWORD: fkweropftj9034
      EMAIL_TIMEOUT: 5
      EMAIL_FROM: netbox@bar.com
      MEDIA_ROOT: /opt/netbox/netbox/media
      NAPALM_USERNAME:
      NAPALM_PASSWORD:
      NAPALM_TIMEOUT: 10
      MAX_PAGE_SIZE: 0
      REDIS_HOST: 
      REDIS_PASSWORD: 
      SECRET_KEY: r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj
      SUPERUSER_NAME: admin
      SUPERUSER_EMAIL: admin@example.com
      SUPERUSER_PASSWORD: admin
      SUPERUSER_API_TOKEN: 0123456789abcdef0123456789abcdef01234567
      WEBHOOKS_ENABLED: false
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    logging:
      driver: json-file

  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.15-alpine
    depends_on:
      - netbox
    volumes:
      - netbox-static-files:/opt/netbox/netbox/static:ro
      - netbox-nginx-config:/etc/netbox-nginx/:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      rap.host: ${DOMAIN}
      rap.le_host: ${DOMAIN}
      rap.port: 8080

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: netbox
    volumes:
      - database:/var/lib/postgres/
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

volumes:
  netbox-nginx-config:
    driver: rancher-nfs
  netbox-static-files:
    driver: rancher-nfs
  netbox-media-files:
    driver: rancher-nfs
  netbox-report-files:
    driver: rancher-nfs
  database:
    driver: rancher-nfs
