version: '2'

catalog:

  name: netbox
  version: 2.5.2
  description: Netbox
  questions:
    - variable: DATABASE_PASSWORD
      label: Database password
      required: true
      type: password
    - variable: DOMAIN
      default: tst3.hoffmann-hosting.de
      label: Domain
      required: true
      type: string
    - variable: LOGIN_REQUIRED
      label: LOGIN REQUIRED
      description: |
      type: enum
      options: # List of options if using type of `enum`
        - true
        - false

services:

  netbox:
    scale: 1
    start_on_create: true

  db:
    scale: 1
    start_on_create: true

  nginx:
    scale: 1
    start_on_create: true
