version: '2'

catalog:

  name: nextcloud
  version: 13.0.2-testing
  description: Nextcloud - Enterprise File Sync and Share
  questions:
    - variable: NC_MYSQL_ROOT_PASS
      label: MySQL root password
      required: true
      type: password
    - variable: NC_MYSQL_PASS
      label: MySQL Pass
      required: true
      type: password
    - variable: NEXTCLOUD_ADMIN_PASSWORD
      label: Nextcloud Admin Password
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  nextcloud:
    scale: 1
    start_on_create: true

  mariadb:
    scale: 1
    start_on_create: true

  redirect-https:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}

  web:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN} 

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}