version: '2'

catalog:

  name: unifi
  version: 5.7.20
  description: Unifi - Wifi Controler
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  unifi:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 8080
        hostname: ${DOMAIN}
      - target_port: 8443
        hostname: ${DOMAIN}
      - target_port: 8843
        hostname: ${DOMAIN}

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}