version: '2'

catalog:

  name: gitea
  version: 1.4
  description: Gitea - Git Server with Web GUI
  questions:
    - variable: DB_PASSWORD
      label: Database Password
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string
    - variable: SSH_PORT
      default: 2222
      label: SSH Port
      required: true
      type: string

services:

  gitea:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: ${DOMAIN}

  database:
    scale: 1
    start_on_create: true

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}