version: '2'

catalog:

  name: rocketchat
  version: 12.0.1
  description: Have your own Slack like online chat, built with Meteor.
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  rocketchat:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: ${DOMAIN}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 20
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000

  mongodb:
    scale: 1
    start_on_create: true

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}