version: '2'

services:

  seafile:
    image: seafileltd/seafile:6.3.4
    volumes:
      - seafile-data:/shared
    environment:
      SEAFILE_SERVER_HOSTNAME: ${DOMAIN}
      SEAFILE_ADMIN_EMAIL: ${ADMIN_EMAIL}
      SEAFILE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    logging:
      driver: none

  proxy:
    image: rancher/lb-service-haproxy:v0.9.1
    expose:
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      traefik.enable: true
      traefik.port: 80
      traefik.acme: true
      traefik.frontend.rule: Host:${DOMAIN}
      rap.host: ${DOMAIN}
      rap.le_host: ${DOMAIN}
      rap.port: 80

volumes:
  seafile-data:
    driver: rancher-nfs