version: '2'

services:

  netbox:
    image: ninech/netbox:v2.5.2
    volumes:
      - netbox-nginx-config:/etc/netbox-nginx/
      - netbox-static-files:/opt/netbox/netbox/static
      - netbox-media-files:/opt/netbox/netbox/media
      - netbox-report-files:/etc/netbox/reports:ro
    depends_on:
      - db
    environment:
      LOGIN_REQUIRED: ${LOGIN_REQUIRED}
      PREFER_IPV4: ${PREFER_IPV4}
      DB_NAME: netbox
      DB_USER: netbox
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_HOST: db
      EMAIL_SERVER: ${EMAIL_SERVER}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_TIMEOUT: 5
      EMAIL_FROM: ${EMAIL_FROM}
      MEDIA_ROOT: /opt/netbox/netbox/media
      NAPALM_USERNAME: ${NAPALM_USERNAME}
      NAPALM_PASSWORD: ${NAPALM_PASSWORD}
      NAPALM_TIMEOUT: 10
      MAX_PAGE_SIZE: 0
      REDIS_HOST: redis
      REDIS_PASSWORD: Grh6fklsd
      SECRET_KEY: ${SECRET_KEY}
      SUPERUSER_NAME: ${SUPERUSER_NAME}
      SUPERUSER_EMAIL: ${SUPERUSER_EMAIL}
      SUPERUSER_PASSWORD: ${SUPERUSER_PASSWORD}
      SUPERUSER_API_TOKEN: ${SUPERUSER_API_TOKEN}
      WEBHOOKS_ENABLED: true
    health_check:
      # Which port to perform the check against
      port: 8001
      # For TCP, request_line needs to be '' or not shown
      # TCP Example:
      # request_line: ''
      request_line: GET /healthcheck HTTP/1.0
      # Interval is measured in milliseconds
      interval: 2000
      initializing_timeout: 120000
      reinitializing_timeout: 120000
      unhealthy_threshold: 3
      # Strategy for what to do when unhealthy
      # In this service, no action will occur when a container is found unhealthy
      strategy: none
      healthy_threshold: 2
      # Response timeout is measured in milliseconds
      response_timeout: 2000
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    logging:
      driver: json-file

  nginx:
    build: https://github.com/stebifan/netbox-nginx.git
    depends_on:
      - netbox
      - db
      - redis
    volumes:
      - netbox-static-files:/opt/netbox/netbox/static:ro
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      traefik.enable: true
      traefik.port: 8080
      traefik.acme: true
      traefik.frontend.rule: Host:${DOMAIN}

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: netbox
    volumes:
      - database:/var/lib/postgresql/data
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

  redis:
    image: redis:4-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass Grh6fklsd ## $$ because of docker-compose
    environment:
      REDIS_PASSWORD: Grh6fklsd
    volumes:
    - netbox-redis-data:/data

volumes:
  netbox-static-files:
    driver: rancher-nfs
  netbox-media-files:
    driver: rancher-nfs
  netbox-report-files:
    driver: rancher-nfs
  netbox-redis-data:
    driver: rancher-nfs
  database:
    driver: rancher-nfs
