version: '2'

catalog:

  name: Grafana + Graphite
  version: 1.1
  description: Grafana Server
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string
    - variable: GRAFANA_PASSWORD
      label: Grafana Password
      required: true
      type: password

services:
  grafana:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: ${DOMAIN}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 3000
      unhealthy_threshold: 10
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
      
  graphite:
    scale: 1
    start_on_create: true
  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}

    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 10
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
