version: '2'

catalog:

  name: seafile
  version: 6.3.4
  description: Seafile - Enterprise File Sync and Share
  questions:
    - variable: ADMIN_PASSWORD
      label: Seafile Admin Password
      required: true
      type: password
    - variable: ADMIN_EMAIL
      default: test@test.de
      label: E-Mail (Login)
      required: true
      type: string
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  seafile:
    scale: 1
    start_on_create: true

  proxy:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${DOMAIN}
        path: /seafhttp
        priority: 1
        protocol: http
        service: seafile
        source_port: 80
        target_port: 80
      - hostname: ${DOMAIN}
        path: /
        priority: 2
        protocol: http
        service: seafile
        source_port: 80
        target_port: 8000
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000