version: '2'

catalog:

  name: openkm
  version: 1
  description: OpenKM
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string


services:

  openkm:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 8080
        hostname: ${DOMAIN}

  redirect-https:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}