version: '2'

catalog:

  name: monitor
  version: 0.2
  description: Docker Monitor
  questions:
    - variable: INFLUXDB_PASSWORD
      label: Influxdb Password
      required: true
      type: password
    - variable: GRAFANA_PASSWORD
      label: Grafana Password
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  influxdb:
   scale: 1
   start_on_create: true

  grafana:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: ${DOMAIN}

  letsencrypt:
    scale: 1
    start_on_create: true