version: '2'

services:

  pretix:
    image: pretix/standalone
    volumes:
      - pretix-data:/data
    depends_on:
      - db
      - redis
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    logging:
      driver: json-file

  redis:
    image: redis:latest

  db:
    image: mariadb:10
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: pretix
      MYSQL_USER: pretix
      MYSQL_PASSWORD: ${DB_PASSWORD}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

volumes:
  pretix-data:
    driver: rancher-nfs
  db:
    driver: rancher-nfs
