version: '2'

catalog:

  name: pretix
  version: 15.0.5
  description: Nextcloud - Enterprise File Sync and Share
  questions:
    - variable: DB_PASSWORD
      label: Database password
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  pretix:
    scale: 1
    start_on_create: true

  db:
    scale: 1
    start_on_create: true

  redis:
    scale: 1
    start_on_create: true
