version: '2'
services:
  Rancher-Active-Proxy:
    image: adi90x/rancher-active-proxy
    environment:
      DEFAULT_HOST: ${DEFAULT_HOST}
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
      CRON: ${CRON}
      DEBUG: ${DEBUG}
      DEFAULT_PORT: ${DEFAULT_PORT}
    stdin_open: true
    volumes:
    - proxy-htpasswd:/etc/nginx/htpasswd
    - proxy-vhost:/etc/nginx/vhost.d
    - proxy-le:/etc/letsencrypt
    - proxy-html:/usr/share/nginx/html
    tty: true
    ports:
    - ${DEFAULT_PORT}:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'

volumes:
  proxy-htpasswd:
    driver: rancher-nfs
  proxy-vhost:
    driver: rancher-nfs
  proxy-le:
    driver: rancher-nfs
  proxy-html:
    driver: rancher-nfs