version: '2'

catalog:

  name: Grafana + Graphite
  version: 0.0.1
  description: Grafana Server
  questions:
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:
  grafana:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
  graphite:
    scale: 1
    start_on_create: true
  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
