version: '2'

catalog:

  name: Grafana + Graphite
  version: 0.0.1
  description: Grafana Server

services:
  grafana:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 3000
        hostname: ${DOMAIN}
  graphite:
    scale: 1
    start_on_create: true
  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}
