version: '2'

services:

  nextcloud:
    privileged: true
    image: nextcloud
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_HOST: 
    links:
    - mariadb:db
    labels:
      io.rancher.container.hostname_override: container_name
    stdin_open: true
    tty: true
    logging:
      driver: syslog

  mariadb:
    image: mariadb:10
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    labels:
      io.rancher.container.hostname_override: container_name

volumes:
  nextcloud:
    driver: rancher-nfs
  mariadb:
    driver: rancher-nfs