version: '2'

services:

  nextcloud:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_HOST: db
    links:
    - mariadb:db
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label: run.on.cm=true
    stdin_open: true
    tty: true
    logging:
      driver: syslog

  mariadb:
    image: mariadb
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label: run.on.cm=true

volumes:
  nextcloud:
    driver: rancher-nfs
  mariadb:
    driver: rancher-nfs