version: '2'

services:

  nextcloud:
    build: https://github.com/stebifan/nc-hoffmann-hosting.git#13.0.5
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - mariadb
    environment:
      DB_DRIVER: mysql
      NC_DB_PASSWORD: ${DB_PASSWORD}
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      DOMAIN: ${DOMAIN}
      SINGLE_USER: ${SINGLE_USER}
      SINGLE_USER_NAME: ${SINGLE_USER_NAME}
      SINGLE_USER_FULL_NAME: ${SINGLE_USER_FULL_NAME}
      SINGLE_USER_QUOTA: ${SINGLE_USER_QUOTA}
      OC_PASS: ${OC_PASS}
    links:
    - mariadb:db
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
    logging:
      driver: json-file

  web:
    image: hoffmannhosting/nc-hoffmann-hosting-nginx
    links:
      - nextcloud:app
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud
    restart: always
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      rap.host: ${DOMAIN}
      rap.le_host: ${DOMAIN}

  db:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: ${DB_PASSWORD}
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always

volumes:
  nextcloud:
    driver: rancher-nfs
  db:
    driver: rancher-nfs
