version: '2'

services:

  nextcloud:
    privileged: true
    image: nextcloud:12-apache
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    ports:
      - ${NEXTCLOUD_PORT}:80
    depends_on:
      - mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_HOST: 
    links:
    - mariadb:db
    labels:
      io.rancher.container.hostname_override: container_name
    stdin_open: true
    tty: true
    logging:
      driver: syslog

  mariadb:
    image: mariadb:10
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    labels:
      io.rancher.container.hostname_override: container_name

volumes:
  nextcloud:
    driver: rancher-nfs
  mariadb:
    driver: rancher-nfs
curl -fsSL -o nextcloud.tar.bz2 "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" && curl -fsSL -o nextcloud.tar.bz2.asc "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 28806A878AE423A28372792ED75899B9A724937A && gpg --batch --verify nextcloud.tar.bz2.asc nextcloud.tar.bz2 && rm -r "$GNUPGHOME" nextcloud.tar.bz2.asc && tar -xjf nextcloud.tar.bz2 -C /usr/src/ && rm nextcloud.tar.bz2 && rm -rf /usr/src/nextcloud/updater && mkdir -p /usr/src/nextcloud/data && mkdir -p /usr/src/nextcloud/custom_apps && chmod +x /usr/src/nextcloud/occ