version: '2'

catalog:

  name: nextcloud
  version: 12.0.1
  description: Nextcloud - Enterprise File Sync and Share
  questions:
    - variable: MYSQL_ROOT_PASS
      label: MySQL root password
      required: true
      type: password
    - variable: MYSQL_PASS
      label: MySQL Pass
      required: true
      type: password
    - variable: NEXTCLOUD_ADMIN_PASSWORD
      label: Nextcloud Admin Password
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  nextcloud:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 80
      unhealthy_threshold: 20
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      reinitializing_timeout: 60000

  mariadb:
    scale: 1
    start_on_create: true

  letsencrypt:
    scale: 1
    start_on_create: true
    lb_config:
      port_rules:
      - target_port: 80
        hostname: ${DOMAIN}