version: '2'

catalog:

  name: nextcloud
  version: 0.0.1
  description: Nextcloud - Enterprise File Sync and Share
  questions:
    - variable: MYSQL_ROOT_PASS
      label: MySQL root password
      required: true
      type: password
    - variable: MYSQL_DATABASE
      default: nextcloud
      label: MySQL Database
      required: true
      type: string
    - variable: MYSQL_USER
      default: nextcloud
      label: MySQL User
      required: true
      type: string
    - variable: MYSQL_PASS
      label: MySQL Pass
      required: true
      type: password
    - variable: DOMAIN
      default: your-domain.de
      label: Domain
      required: true
      type: string

services:

  nextcloud:
    scale: 1
    start_on_create: true

  mariadb:
    scale: 1
    start_on_create: true